environments:
  production:
    kubeContext: docker-desktop
---
repositories:
  - name: friendly-octo-guacamole
    url: https://erdincakgun.github.io/friendly-octo-guacamole
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: strimzi
    url: https://strimzi.io/charts
releases:
  - name: friendly-octo-guacamole
    namespace: "{{ .Environment.Name }}"
    createNamespace: true
    chart: friendly-octo-guacamole/friendly-octo-guacamole
    version: 1.2.0
    values:
      - values/{{ .Environment.Name }}/friendly-octo-guacamole.yaml
  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.14.1
  - name: grafana
    needs:
      - ingress-nginx/ingress-nginx
    namespace: central-observability
    createNamespace: true
    chart: grafana/grafana
    version: 10.3.0
    values:
      - values/{{ .Environment.Name }}/grafana.yaml
    secrets:
      - values/{{ .Environment.Name }}/grafana.sops.yaml
  - name: strimzi-kafka-operator
    namespace: monitoring
    createNamespace: true
    chart: strimzi/strimzi-kafka-operator
    version: 0.49.1
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "manifests/{{ .Environment.Name }}/kafka.yaml"
          - "-n"
          - "monitoring"
          - "--context"
          - "{{ .Environment.KubeContext }}"
