environments:
  production:
    kubeContext: docker-desktop
---
repositories:
  - name: friendly-octo-guacamole
    url: https://erdincakgun.github.io/friendly-octo-guacamole
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: strimzi
    url: https://strimzi.io/charts
  - name: fluent
    url: https://fluent.github.io/helm-charts
  - name: kafka-ui
    url: https://ui.charts.kafbat.io/
  - name: minio
    url: https://operator.min.io/
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: stevehipwell
    url: https://stevehipwell.github.io/helm-charts/
releases:
  - name: friendly-octo-guacamole
    namespace: "{{ .Environment.Name }}"
    createNamespace: true
    chart: friendly-octo-guacamole/friendly-octo-guacamole
    version: 1.2.0
    values:
      - values/{{ .Environment.Name }}/friendly-octo-guacamole.yaml
  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.14.1
  - name: strimzi-kafka-operator
    namespace: monitoring
    createNamespace: true
    chart: strimzi/strimzi-kafka-operator
    version: 0.49.1
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "manifests/{{ .Environment.Name }}/kafka.yaml"
          - "-n"
          - "monitoring"
          - "--context"
          - "{{ .Environment.KubeContext }}"
  - name: fluent-bit
    needs:
      - strimzi-kafka-operator
    namespace: monitoring
    createNamespace: true
    chart: fluent/fluent-bit
    version: 0.54.0
    values:
      - values/{{ .Environment.Name }}/fluent-bit.yaml
  - name: kafka-ui
    needs:
      - strimzi-kafka-operator
    namespace: monitoring
    createNamespace: true
    chart: kafka-ui/kafka-ui
    version: 0.7.3
    values:
      - values/{{ .Environment.Name }}/kafka-ui.yaml
  - name: grafana
    needs:
      - ingress-nginx/ingress-nginx
      - central-observability/loki
      - central-observability/thanos
    namespace: central-observability
    createNamespace: true
    chart: grafana/grafana
    version: 10.3.0
    values:
      - values/{{ .Environment.Name }}/grafana.yaml
    secrets:
      - values/{{ .Environment.Name }}/grafana.sops.yaml
  - name: minio-operator
    namespace: central-observability
    createNamespace: true
    chart: minio/operator
    version: 7.1.1
    values:
      - values/{{ .Environment.Name }}/minio-operator.yaml
  - name: minio
    needs:
      - minio-operator
    namespace: central-observability
    createNamespace: true
    chart: minio/tenant
    version: 7.1.1
    values:
      - values/{{ .Environment.Name }}/minio.yaml
    secrets:
      - values/{{ .Environment.Name }}/minio.sops.yaml
  - name: loki
    needs:
      - central-observability/minio
      - monitoring/strimzi-kafka-operator
    namespace: central-observability
    createNamespace: true
    chart: grafana/loki
    version: 6.46.0
    values:
      - values/{{ .Environment.Name }}/loki.yaml
    secrets:
      - values/{{ .Environment.Name }}/loki.sops.yaml
  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    version: 3.13.0
    values:
      - values/{{ .Environment.Name }}/metrics-server.yaml
  - name: open-telemetry-collector
    namespace: monitoring
    chart: open-telemetry/opentelemetry-collector
    version: 0.140.1
    values:
      - values/{{ .Environment.Name }}/open-telemetry-collector.yaml
  - name: kube-prometheus-stack
    needs:
      - central-observability/thanos
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 79.12.0
    values:
      - values/{{ .Environment.Name }}/kube-prometheus-stack.yaml
  - name: thanos
    needs:
      - central-observability/minio
    namespace: central-observability
    chart: stevehipwell/thanos
    version: 1.22.0
    values:
      - values/{{ .Environment.Name }}/thanos.yaml
    secrets:
      - values/{{ .Environment.Name }}/thanos.sops.yaml
